export const moviesData = [
    {
        genreTags: ["action", "adventure"],
        isSeries: false,
        image: "madmax.jpg",
        alt: "Mad Max Fury Road poster",
        title: "Mad Max: Fury Road",
    },
    {
        genreTags: ["action", "sci-fi"],
        isSeries: false,
        image: "matrix.jpg",
        alt: "The Matrix poster",
        title: "The Matrix",
    },
    {
        genreTags: ["comedy", "family"],
        isSeries: false,
        image: "paddington.jpg",
        alt: "Paddington poster",
        title: "Paddington",
    },
    {
        genreTags: ["comedy", "romance"],
        isSeries: false,
        image: "crazyrichasians.jpg",
        alt: "Crazy Rich Asians poster",
        title: "Crazy Rich Asians",
    },
    {
        genreTags: ["horror", "thriller"],
        isSeries: false,
        image: "quietplace.jpg",
        alt: "A Quiet Place poster",
        title: "A Quiet Place",
    },
    {
        genreTags: ["thriller", "mystery"],
        isSeries: false,
        image: "gonegirl.jpg",
        alt: "Gone Girl poster",
        title: "Gone Girl",
    },
    {
        genreTags: ["animation", "family"],
        isSeries: false,
        image: "coco.jpg",
        alt: "Coco poster",
        title: "Coco",
    },
    {
        genreTags: ["animation", "adventure"],
        isSeries: false,
        image: "spiderverse.jpg",
        alt: "Spider-Man Into the Spider-Verse poster",
        title: "Spider-Man: Into the Spider-Verse",
    },
    {
        genreTags: ["drama", "romance"],
        isSeries: false,
        image: "laland.jpg",
        alt: "La La Land poster",
        title: "La La Land",
    },
    {
        genreTags: ["drama", "sports"],
        isSeries: false,
        image: "creed.jpg",
        alt: "Creed poster",
        title: "Creed",
    },
    {
        genreTags: ["sci-fi", "drama"],
        isSeries: false,
        image: "interstellar.jpg",
        alt: "Interstellar poster",
        title: "Interstellar",
    },
    {
        genreTags: ["fantasy", "adventure"],
        isSeries: false,
        image: "lotr.jpg",
        alt: "Lord of the Rings poster",
        title: "The Lord of the Rings",
    },
    {
        genreTags: ["crime", "drama"],
        isSeries: true,
        image: "breakingbad.jpg",
        alt: "Breaking Bad poster",
        title: "Breaking Bad",
    },
    {
        genreTags: ["crime", "thriller"],
        isSeries: true,
        image: "moneyheist.jpg",
        alt: "Money Heist poster",
        title: "Money Heist",
    },
    {
        genreTags: ["fantasy", "drama"],
        isSeries: true,
        image: "houseofthedragon.jpg",
        alt: "House of the Dragon poster",
        title: "House of the Dragon",
    },
    {
        genreTags: ["comedy", "series"],
        isSeries: true,
        image: "theoffice.jpg",
        alt: "The Office poster",
        title: "The Office",
    },
    {
        genreTags: ["mystery", "sci-fi"],
        isSeries: true,
        image: "dark.jpg",
        alt: "Dark poster",
        title: "Dark",
    },
    {
        genreTags: ["action", "series"],
        isSeries: true,
        image: "reacher.jpg",
        alt: "Reacher poster",
        title: "Reacher",
    },
    {
        genreTags: ["family", "series"],
        isSeries: true,
        image: "avatarlastairbender.jpg",
        alt: "Avatar The Last Airbender poster",
        title: "Avatar: The Last Airbender",
    },
    {
        genreTags: ["sports", "comedy"],
        isSeries: true,
        image: "tedlasso.jpg",
        alt: "Ted Lasso poster",
        title: "Ted Lasso",
    }
]